baseURL = "https://benawise.com/"
languageCode = "en-us"
title = "Ben A. Wise"
theme = "minimal"

[params]
  description = "Personal blog of Ben A. Wise"
  author = "Ben A. Wise"

[outputs]
  home = ["HTML", "RSS"]
  section = ["HTML"]
  taxonomy = ["HTML"]
  term = ["HTML"]

[server]
  [[server.headers]]
    for = "/**"
    [server.headers.values]
      Cache-Control = "public, max-age=31536000"

[build]
  useResourceCacheWhen = "always"

[minify]
  minifyOutput = true

[assets]
  disableHLJS = true
  disableFingerprinting = false
